version: '3.8'

services:
  markdown-preview:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - RUST_LOG=info
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development version with hot reload
  markdown-preview-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - RUST_LOG=debug
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
      - /app/target
    restart: unless-stopped
    profiles:
      - dev 