app: markdown-preview

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - RUST_LOG=info
      - RUST_ENV=production
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

domains:
  - markdown-preview.dokploy.com

env:
  - NODE_ENV=production
  - RUST_ENV=production
  - BACKEND_PORT=3001
  - FRONTEND_PORT=3000 