[phases.setup]
nixPkgs = ["rustc", "cargo", "nodejs_18", "npm-9_x"]

[phases.install]
cmds = [
  "npm install",
  "cd frontend && npm install"
]

[phases.build]
cmds = [
  "cargo build --release",
  "cd frontend && npm run build"
]

[start]
cmd = "cargo run --release" 