# Log configuration for Markdown Preview
version: 1

formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  json:
    format: '{"timestamp": "%(asctime)s", "level": "%(levelname)s", "name": "%(name)s", "message": "%(message)s"}'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: logs/markdown-preview.log
    maxBytes: 10485760  # 10MB
    backupCount: 5

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: json
    filename: logs/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 3

loggers:
  markdown_preview:
    level: INFO
    handlers: [console, file, error_file]
    propagate: false

  axum:
    level: INFO
    handlers: [console, file]
    propagate: false

  tokio:
    level: WARN
    handlers: [console, file]
    propagate: false

root:
  level: INFO
  handlers: [console] 